I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/chapter4.rpy", line 57, in script
    if p.conversations_had < 10:
  File "game/story/chapter4.rpy", line 57, in <module>
    if p.conversations_had < 10:
AttributeError: 'Player' object has no attribute 'conversations_had'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/chapter4.rpy", line 57, in script
    if p.conversations_had < 10:
  File "C:\Users\alexs\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\alexs\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\alexs\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/story/chapter4.rpy", line 57, in <module>
    if p.conversations_had < 10:
AttributeError: 'Player' object has no attribute 'conversations_had'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
WacBonalds 1.0
Wed Nov 22 14:06:33 2023
